# Generated by Django 5.2.6 on 2025-09-25 03:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_ocrresult_image_alter_ocrresult_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ocrresult',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='ocrresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_results', to=settings.AUTH_USER_MODEL),
        ),
    ]
